Article.create(title: "Article 1", description: "article desc 1")
Article.create(title: "Article 2", description: "article desc 2")
Article.create(title: "Article 3", description: "article desc 3")
Article.create(title: "Article 4", description: "article desc 4")
Article.create(title: "Article 5", description: "article desc 5")